version: '3.8'
services:
  mongo:
    container_name: mongo-container
    image: mongo:6
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - '27017:27017'
  api:
    container_name: api-container
    build: .
    restart: always
    image: clean-ts-api
    command: npm start
    volumes:
      - ./dist:/usr/src/clean-ts-api
    ports:
      - '3030'
    links:
      - mongo
